name: ping

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase
        run: |
          curl -X GET "https://ccahshwqplmmavjeaujv.supabase.co"
